apiVersion: apps/v1
kind: Deployment
metadata:
  name: sk071-myfirst-api-server
  namespace: skala-practice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sk071-myfirst-api-server
  template:
    metadata:
      annotations:
        prometheus.io/scrape: 'true'
        prometheus.io/port: '8080'
        prometheus.io/path: '/actuator/prometheus'
        update: 4ca757fa
      labels:
        app: sk071-myfirst-api-server
    spec:
      serviceAccountName: default
      containers:
      - name: myfirst-api-server
        image: gwangun/sk071-server:88a2fe7fba0707b4622b9e7c1cf91b8f9148c7db
        imagePullPolicy: Always
        env:
        - name: USER_NAME
          value: sk071
        - name: NAMESPACE
          value: skala-practice
        - name: SPRING_PROFILES_ACTIVE  
          value: "prod"  

# test direct k8s change