apiVersion: apps/v1
kind: Deployment
metadata:
  name: sk071-myfirst-api-server
  namespace: default                    
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sk071-myfirst-api-server
  template:
    metadata:
      annotations:
        prometheus.io/scrape: 'true'
        prometheus.io/port: '8080'
        prometheus.io/path: '/actuator/prometheus'
        update: 4ca757fa
      labels:
        app: sk071-myfirst-api-server
    spec:
      serviceAccountName: default
      containers:
      - name: myfirst-api-server
        image: gwangun/sk071-server:49e4bb58db2f879a89ffad1be727768cb78a5049
        imagePullPolicy: Always
        env:
        - name: USER_NAME
          value: sk071
        - name: NAMESPACE
          value: default                
        - name: SPRING_PROFILES_ACTIVE  
          value: "dev"                  