apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: sk071-myfirst-ingress
  namespace: default          
spec:
  rules:
  - host: sk071.local         # 로컬 도메인으로 변경
    http:
      paths:
      - backend:
          service:
            name: sk071-myfirst-api-server
            port:
              number: 8080
        path: /
        pathType: Prefix